services:
  fxserver:
    image: traskin/fxserver:${ARTIFACT_VERSION:-recommended}
    ports:
      - 30120:30120/tcp
      - 30120:30120/udp
      - 40120:40120
    volumes:
      - ./FiveM Servers/${FIVEM_SERVER_NAME}/txData:/txData
    links:
      - mariadb
    depends_on:
      - mariadb
      - phpmyadmin
  mariadb:
      image: mariadb:10.5.16
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
          - "3306:3306"
      volumes:
          - mariadbdata:/var/lib/mysql
      environment:
          - MYSQL_DATABASE=${FIVEM_SERVER_NAME}
          - MYSQL_USER=root
          - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:4.8.5
      restart: always
      depends_on:
          - mariadb
      environment:
          - PMA_HOST=mariadb
          - PMA_PORT=3306
          - PMA_USER=root
          - PMA_PASSWORD=
      ports:
          - "3333:80"
volumes:
  mariadbdata:
